### ISSUE TITLE
[Track 1] Codalab Submission Error

### ISSUE THREAD

**Issue by SheffieldCao** [robodrive-24/toolkit#3]
I submitted a zipped file (test.zip) following the folder structure given in the tutorials, but I got the following evaluation error. 😂 Does anyone know where the problem is.

My folder structure:

```shell
.
├── brightness
│   └── results_nusc.json
├── color_quant
│   └── results_nusc.json
├── contrast
│   └── results_nusc.json
...
├── snow
│   └── results_nusc.json
└── zoom_blur
│   └── results_nusc.json
```

> WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/tmp/codalab/tmp1DiR1k/run/program/evaluate.py", line 646, in 
    metric_mean = evaluate_main(nusc, submit_path)
  File "/tmp/codalab/tmp1DiR1k/run/program/evaluate.py", line 550, in evaluate_main
    with open(results_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmp1DiR1k/run/input/res/pred.json'

**Comment by robodrive-24** [comment]
Hi @SheffieldCao, thanks for your participation in the RoboDrive challenge!

Regarding your question:
- Kindly follow the newest instructions as listed [here](https://github.com/robodrive-24/toolkit/tree/main/track-1), where we squeeze all subfiles into a single file named `pred.json`.
- Zip compress `pred.json`, e.g., `pred.json.zip`, and submit it to the CodaLab server.
- We have provided the prediction file generated using the baseline model. You can download it from [here](https://drive.google.com/drive/folders/1rbpRKTsFhQc-Una53hixKgZjo0PM0bSL?usp=drive_link).

Let us know if the above solves your problem!

**Comment by SheffieldCao** [comment]
OK, I will try the new way. Thank you!

> Hi @SheffieldCao, thanks for your participation in the RoboDrive challenge!
> 
> Regarding your question:
> 
> * Kindly follow the newest instructions as listed [here](https://github.com/robodrive-24/toolkit/tree/main/track-1), where we squeeze all subfiles into a single file named `pred.json`.
> * Zip compress `pred.json`, e.g., `pred.json.zip`, and submit it to the CodaLab server.
> * We have provided the prediction file generated using the baseline model. You can download it from [here](https://drive.google.com/drive/folders/1rbpRKTsFhQc-Una53hixKgZjo0PM0bSL?usp=drive_link).
> 
> Let us know if the above solves your problem!

**Comment by SheffieldCao** [comment]
There seem still some obvious bugs in `convert_submit.py`, but it doesn't matter, I have fixed them by myself. Just a kind reminder.  😂

**Comment by robodrive-24** [comment]
> There seem still some obvious bugs in `convert_submit.py`, but it doesn't matter, I have fixed them by myself. Just a kind reminder. 😂

Thanks for letting us know!
