### ISSUE TITLE
Track 2 training problem

### ISSUE THREAD

**Issue by Yolan1013** [robodrive-24/toolkit#6]
Hello! 
I've followed the installation.md and convert the trainval.pkl following BEVerse, but meet this question when running configs/robodrive/beverse_small.py. And I can run configs/beverse/beverse_small.py normally. Could you help me with
![1](https://github.com/robodrive-24/toolkit/assets/34823398/6ba5e425-081a-4c2c-9d37-7d57a7a0f66c)
 it?

**Comment by robodrive-24** [comment]
Hi @Yolan1013  , thanks for your participation in the RoboDrive challenge!

Regarding your question:

Please only use `configs/robodrive/beverse_small.py` for inference. For training, please use the configuration file under `beverse` folder.

Let us know if the above solves your problem!

**Comment by Yolan1013** [comment]
Thanks for your reply! My problem has been solved.
